// USER

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_DATA";
export const FETCHING_USER_FAILED = "FETCHING_USER_FAILED";
export const FETCHING_MESSAGE = "FETCHING_MESSAGE";
export const FETCH_MESSAGE_FAILED = "FETCH_MESSAGE_FAILED";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
